apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zcorp
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: zcorp
        tier: app
    spec:
      containers:
        - name: api
          image: zcorp-api:v2
          resources:
              limits:
                cpu: 100m
                memory: 512Mi
          ports:
            - name: http
              containerPort: 8080