apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-volume
spec:
  # here we are defining a volume available to the cluster
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/mysql/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  # here we are requesting access to a volume with a size of 2 gigabytes
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi