kind: Service
apiVersion: v1
metadata:
  name: zcorp
spec:
  type: NodePort
  selector:
    app: zcorp
    tier: api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http