kind: Service
apiVersion: v1
metadata:
  name: zcorp
spec:
  type: NodePort
  selector:
    # determines where the traffic should go
    # these labels match what is in our api-deployment.yml
    app: zcorp
    tier: api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http