apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    # determines where the traffic should go
    # these labels match what is in our mysql-deployment.yml
  app: mysql
  ports:
    - name: mysql
      port: 3306
  clusterIP: None